[package]
name = "BTS2"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
crossbeam-channel = "0.5"
libc = "0.2"
needletail = "0.6"
packed-seq = { git = "https://github.com/rust-seq/packed-seq.git" }
simd-minimizers = { git = "https://github.com/rust-seq/simd-minimizers.git" }
regex = "1.11"
rustc-hash = "2.1"
sux = "0.7"

[profile.release]
opt-level = 3
lto = "fat"

[profile.dev]
opt-level = 1
lto = "thin"
