[package]
name = "BTS2"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
needletail = "0.6"
nthash = "0.5"
minimizer-iter = "1.2"
simd-minimizers = "1.1"
fxhash = "0.2"
flate2 = "1.0"
zstd = "0.13"
rayon = "1.5"
packed-seq = "2.0"
crossbeam-channel = "0.5"
ahash = "0.8"
seq_io = "0.3"
seq_io_parallel = "0.2"
niffler = "3.0"
memory-stats = "1.2"

[profile.release]
opt-level = 3
lto = "fat"

[profile.dev]
opt-level = 1
lto = "thin"
